device:
  - cpu
model:
  - CGMM
batch_size:
  - 2000
l_prec:
  - [1]
max_layers:
  - 3
A:
  - 1
C:
  - 20
node_type:
  - discrete 
unibigram:
  - False
aggregation:
  - mean  # Not used with CGMMPPI!
infer_with_posterior:
  - True
max_epochs:
  - 10
threshold:
  - 0.
self_arc:
  - False
learning_rate:
  - 0.01
l2:
  - 0.00001
classifier_epochs:
  - 1000
hidden_units:
  - 128
#  - 256
#  - 512
optimizer:
  - Adam
gradient_clipping:
  - null
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: False
