model:
  - DGI
device:
  - cuda
batch_size:
  - 1
learning_rate:
  - 0.001
  - 0.0001
DGI_epochs:
  - 20
  - 50
optimizer:
  - Adam
scheduler:
  - null
gradient_clipping:
  - null
shuffle:
  - True
dropout:
  - 0.
  - 0.25
  - 0.5
dim_embedding:
  - 128
  - 256
  - 512
training_strategy:
  - one_vs_all
  - all_vs_all